### ISSUE TITLE
Pandas/Numpy issue in Galaxy with py2_isatools-lite

### ISSUE THREAD

**Issue by pkrog** [ISA-tools/isa-api#253] opened 2017-10-29 09:56 UTC
Hi @djcomlab ,
Using the py2_isatools-lite branch to install isatools inside Galaxy for ISA datatype, I get the following error on `from isatools import isatab`:
```
galaxy.datatypes.registry ERROR 2017-10-29 09:28:33,216 Error importing datatype module galaxy.datatypes.isa: numpy.dtype has the wrong size, try recompiling. Expected 88, got 96
Traceback (most recent call last):
  File "/Users/pierrick/dev/galaxy-isatab/lib/galaxy/datatypes/registry.py", line 209, in load_datatypes
    module = __import__( datatype_module )
  File "/Users/pierrick/dev/galaxy-isatab/lib/galaxy/datatypes/isa.py", line 21, in <module>
    from isatools import isatab #==> XXX ImportError: cannot import name zip_longest. Is isatools compatible with Python 2.7?
  File "/Users/pierrick/dev/isa-api/isatools/isatab.py", line 17, in <module>
    import pandas as pd
  File "/Users/pierrick/dev/galaxy-isatab/.venv/lib/python2.7/site-packages/pandas/__init__.py", line 26, in <module> 
    from pandas._libs import (hashtable as _hashtable,
  File "/Users/pierrick/dev/galaxy-isatab/.venv/lib/python2.7/site-packages/pandas/_libs/__init__.py", line 4, in <module>
    from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
  File "pandas/_libs/src/numpy.pxd", line 157, in init pandas._libs.tslib
ValueError: numpy.dtype has the wrong size, try recompiling. Expected 88, got 96
```

NumPy is set to version 1.9.2 by Galaxy, and pip insists on install only Pandas latest version (0.21.0).
What can I do?

**Comment by djcomlab** [comment] 2017-10-30 10:30
Can you manually install an earlier Pandas version? I have it with Pandas 0.20.3 and Numpy 1.13.3 working OK.

Also I see the `ImportError: cannot import name zip_longest` - it should import from `six.moves` now.

I did test this with tox in py27 environment as well, installing whatever latest dependencies.

**Comment by djcomlab** [comment] 2017-10-31 11:05
What is the reason Galaxy is fixed to an old NumPy version?

**Comment by djcomlab** [comment] 2017-10-31 11:12
Marking as a `distribution issue` as this is a problem when using an old version of NumPy (1.9.2) that is not compatible with the latest Pandas. The NumPy version that https://github.com/galaxyproject/galaxy/ uses is pinned to 1.9.2.

**Comment by djcomlab** [comment] 2017-10-31 11:32
OK so the problem is that becuase NumPy is fixed to 1.9.2 in Galaxy, distributions of Pandas - even if specifying older Pandas versions - are likely to have already been compiled against newer versions of NumPy. The binary compiled parts of Pandas might not be backward compatible.

**Comment by djcomlab** [comment] 2017-10-31 11:38
@pkrog Please try use `pandas==0.15.2`. I would recommend you ask Galaxy devs if they could upgrade NumPy unless there's a good reason not to, as this is 6 major releases behind the current Pandas version.

**Comment by djcomlab** [comment] 2017-10-31 12:31
Hi @pkrog actually after exhaustively testing a few more versions I think the following `pandas`/`numpy` requirements should work:

```
pandas==0.20.1
numpy==1.9.2
```

**Comment by djcomlab** [comment] 2017-10-31 12:48
@pkrog Please try use `requirements-galaxy.txt` that was just pushed.

**Comment by djcomlab** [comment] 2017-11-02 16:26
I've now tested this quite extensively against the Galaxy pinned-requirements.txt (https://github.com/phnmnl/galaxy/blob/dev/lib/galaxy/dependencies/pinned-requirements.txt) and updated the `isatools` requirements on the branch accordingly, so closing...

**Closed by djcomlab** 2017-11-02 16:26 UTC
Labels: distribution issue
