### ISSUE TITLE
Test failure on branch py2_isatools-lite with MTBLS30-2

### ISSUE THREAD

**Issue by pkrog** [ISA-tools/isa-api#265] opened 2017-11-07 11:31 UTC
I've added test for MTBLS30-2 (MTBLS30 latest version from Metabolights) inside branch pkrog:py2_isatools-lite-mtbls30-testing, and get the following error:
```
======================================================================
ERROR: test_isatab_load_bii_s_7 (tests.test_isatab.InvestigationParserIntegrationTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/pierrick/dev/isa-api/tests/test_isatab.py", line 409, in test_isatab_load_bii_s_7
    self.parser.parse(fp)
  File "/Users/pierrick/dev/isa-api/isatools/isatab.py", line 80, in parse
    self._parse(filepath_or_buffer)
  File "/Users/pierrick/dev/isa-api/isatools/isatab.py", line 614, in _parse
    section_slices = self._split_investigation_table(filebuffer)
  File "/Users/pierrick/dev/isa-api/isatools/isatab.py", line 229, in _split_investigation_table
    for sec_index, row in enumerate(tabreader):
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb0' in position 591: ordinal not in range(128)
```
There is indeed a "degree sign" at line 72 of file "i_Investigation.txt". Why does it raise an error? Are files not read in UTF-8 encoding by default?

**Comment by djcomlab** [comment] 2017-11-07 12:42
It does read UTF-8, and ISA-Tabs should all be encoded as such. The problem is that the degree character found in MTBLS30 is not UTF-8.

**Comment by pkrog** [comment] 2017-11-07 13:05
Oh ! ok. So there's no way the study is going to be parsed correctly. However I've used it inside my tests in isatab2w4m. Why should it fail now? Python 2.7 effect?

**Comment by djcomlab** [comment] 2017-11-07 13:11
I'm just looking into it...

`io.open()` has a parameter `errors`  that can help be more resilient when doing `io.open('myfile', encoding='utf-8', errors='replace')`, but it breaks some other tests if I add this in places. 

It doesn't behave like this in Python 3, but UTF-8 is natively handled in Python 3 but not in Python 2.

**Comment by djcomlab** [comment] 2017-11-07 13:17
We can maybe find a way to maybe preprocess the input files to ensure non-UTF-8 characters are dealt with somehow or stripped out. The problem comes down to mixed encodings. In this case the majority of the ISA-Tab file is UTF-8, but obviously in the description the submitter must have copy-pasted text from a  non-UTF-8 source resulting in this mixed content encoding.

Ideally MetaboLights should fix these instances as it is off-spec but it happens often enough that the parsers should be fixed to deal with it.

**Comment by pkrog** [comment] 2017-11-08 10:53
I've looked into the `i_Investigation.txt` file, and the degree sign is rightly encoded in UTF-8:
```
00001b90: 6420 2832 3320 c2b0 4329 2066 6163 696c  d (23 ..C) facil
```
As you see it is encoded as 'c2b0' (<http://www.fileformat.info/info/unicode/char/b0/index.htm>).
So the method must really be expecting ascii and not UTF-8.

**Comment by pkrog** [comment] 2017-11-08 11:03
I confirm I get no issue with Python 3.6.

**Comment by pkrog** [comment] 2017-11-08 11:18
The default encoding used by `io.open()` is the one defined in the locale. So UTF-8 for me. The file is read correctly by `io.open()`.
What happens is that for some reason in
```python
for sec_index, row in enumerate(tabreader):
```
the Unicode string is forced to be converted into ASCII, hence failure.

**Comment by pkrog** [comment] 2017-11-08 11:46
`csv.reader()` is different between Python 2 and Python 3. The version in Python 2 requires the file to be opened in binary mode (see <https://docs.python.org/2/library/io.html#io.open>).

**Comment by pkrog** [comment] 2017-11-08 13:28
I've added a function to handle opening of file in both Python 2 and 3, inside `test_isatab.py`.
Maybe it would be safer for the `parse()` method to take also a path instead of a file object. The opening would then be handled inside isatools.

**Comment by djcomlab** [comment] 2017-11-14 10:26
Thanks @pkrog, will take a look

**Comment by djcomlab** [comment] 2017-12-08 10:31
Added to https://github.com/ISA-tools/isa-rwval/commit/365a0c7b5d248074f867a67d9348e69421c2f99d, closing since this branch work is being moved to work in https://github.com/ISA-tools/isa-rwval/

**Closed by djcomlab** 2017-12-08 10:31 UTC
