### ISSUE TITLE
isatab2json problem in new isa-tools version v0.10.4

### ISSUE THREAD

**Issue by bedroesb** [ISA-tools/isa-api#344] opened 2019-10-22 15:26 UTC
When using the ISA2json conversion with isatools v0.10.4 in following code:

```python
                input_file_path = output_directory
                output_file_path = output_directory + filenameFormat(trial['trialName']) + '.json'

                isa_json = isatab2json.convert(
                input_file_path, use_new_parser=True, validate_first=False)
                with open(output_file_path, 'w') as out_fp:
                    json.dump(isa_json, out_fp, indent=4)
```

Gives:

```bash
2019-10-22 14:49:08,289 [INFO]: isatab2json.py(convert:53) >> Using new ISA-Tab parser
2019-10-22 14:49:08,289 [INFO]: isatab2json.py(convert:54) >> Loading ISA-Tab: outputdir/POPYOMICS/i_investigation.txt
2019-10-22 14:49:08,539 [INFO]: brapi_to_isa.py(main:470) >> 'NoneType' object has no attribute 'comments'
```

This is not a problem with `use_new_parser=False`.

**Comment by proccaserra** [comment] 2019-10-24 08:25
@bedroesb can you send me popyomics isatab output? or tell me which endpoint you are hitting?
thx

**Comment by proccaserra** [comment] 2019-10-24 15:51
@bedroesb investigating this issue uncorvered 2 things:
1. an issue related to the use of `NA` string by brapi2isa.py to supply a missing value in the i_investigation.txt file
We rely on Pandas to parse the tab files which means that , when hitting 'NA', Pandas casts the object as None (see [pandas documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html) ).
In the case of 'study design descriptors' (as in the "poppyomics" dataset example), since the follow to the descriptor has been set to 'NA' by brapi2isa, the object is set to 'None' and  no `ISA comments` can be attached to such object. This causes the first problem which you reported.
It manifests itself with the isa read function and thus in the isa convert.

2. an omission in the `isajson` serializer in the `get_ontology_annotation` method
this meant that `comments` attached to an `OntologyAnnotation` wouldn't be output in the ISAJSON documents.

these 2 things are now fixed, running tests now, pushing to dev soon.

**Comment by bedroesb** [comment] 2019-10-25 08:12
@proccaserra thank you for the explanation. Looking forward to test the update!

**Comment by proccaserra** [comment] 2019-10-25 08:14
@bedroesb I pushed to brag_to_isa dev branch on elixir_europe. it is minimal and should make sure the result ISA-Tab document (investigation file) are fine. 
We also our side of the issue. thx for reporting.

**Comment by bedroesb** [comment] 2019-10-25 09:27
@proccaserra  At this moment we make a distinction between not available in the endpoint and not in Brapi see https://github.com/elixir-europe/plant-brapi-to-isa#unavailable-values. The values you change can be read out from BrAPI. Is N.A. seen as nontype  by pandas?

**Comment by bedroesb** [comment] 2019-10-25 09:28
I thought you would handle the problem on you side :)

**Comment by proccaserra** [comment] 2019-10-25 09:34
@bedroesb we need both I am afraid. It is really an issue caused by the use of python Pandas when parsing. Also, it only manifests itself when reading the i_investigation.txt file for objects such as `Study Design` and `Contact Role` when `Comment[]` are attached to those.
If BRAPI code sets the value for `Study Design` and `Contact Role` to `NA` or any other `missing value` recognised by pandas, pandas will set the entity to None, which results in the impossibility of attaching `Comment` to it.
Hence my push to `Brapi_to_ISA_converter.py`. It seems that there is a need to be able to distinguish between `NA in BrAPI` and `NA in endpoint`, may be the latter should be just that explicit.

**Comment by bedroesb** [comment] 2019-10-25 09:35
I think it is important to be consistent with these NA things. So we could change PAR_NAinData value to a value that is not seen by pandas as a nontype. So it is everywhere the same at least

**Closed** 2021-03-01 16:04 UTC
