### ISSUE TITLE
Incorrect parsing of the Comments field for Study Contacts

### ISSUE THREAD

**Issue by pablormier** [ISA-tools/isa-api#286] opened 2017-12-08 10:54 UTC
ISA Creator 1.7 stores the custom fields added to an study contact as 'Comment [Name]'. However, the isatab module (v 0.9.3) tries to parse it by looking for lines starting with 'Comment[' which is incorrect. The problem is [here](https://github.com/ISA-tools/isa-api/blob/817a7abbcc9e84b48b047dfc1ea1f2955bcadd39/isatools/isatab.py#L3011
)

```
def get_comments_row(cols, row):
        comments = []
        for col in [x for x in cols if str(x).startswith("Comment[")]:
            comment = Comment(name=col[8:-1], value=row[col])
            comments.append(comment)
        return comments
```
Not sure if it's a bug in ISA Creator or ISA API. I think the problem is in ISA Creator since in other places, comments are inserted as 'Comment[..]'

**Comment by djcomlab** [comment] 2017-12-08 11:00
Hi @pablormier, thanks for the report - just to clarify, the problem is the whitespace between `Comment` and `[`, correct?

i.e. `Comment[name]` vs `Comment [name]`

**Comment by agbeltran** [comment] 2017-12-08 11:19
It looks like a problem in ISAcreator.

**Comment by djcomlab** [comment] 2017-12-08 11:22
Well, although the references to these kinds of labels in the ISA-Tab specification all omit this whitespace, the spec doesn't actually specify that you can't have whitespace in between the label and the square brackets.

Should we allow these cases if ISAcreator has been producing such output?

**Comment by proccaserra** [comment] 2017-12-08 11:40
We'll to support it by not failing on such errors. Some tools (including ISAcreator using specific configurations) may produce such artefacts but I feel the reader should be able to deal with them.
As for the specifications, they should disallow with whitespace between syntactic tags and the bracket.

**Comment by djcomlab** [comment] 2017-12-08 11:43
I guess lint-level syntactic checks could report the whitespace as warnings, but the tooling should allow it for usability.

**Comment by djcomlab** [comment] 2017-12-08 12:01
I will add a regex `Comment\s*\[(.*?)\]` to parse the Comments labels

**Comment by pablormier** [comment] 2017-12-08 18:22
Thank you so much

**Comment by djcomlab** [comment] 2017-12-19 15:51
Completed in develop, fix will be present in next release. Closing this issue...

**Closed by djcomlab** 2017-12-19 15:51 UTC
Labels: bug
