### ISSUE TITLE
Parser giving warning when 'Protocol REF' is not immediately before a 'Data Transformation'

### ISSUE THREAD

**Issue by agbeltran** [ISA-tools/isa-api#235] opened 2017-08-15 17:35 UTC
When a 'Protocol REF' includes parameter values that have Term Source REF and Term Accession before the 'Data Transformation Name', the parser is giving some warnings, even if the files are correct.

Output:
```
warning: Protocol REF missing before 'Data Transformation Name', found 'Term Accession Number'
inserting Protocol REF.3 at position 46
warning: Protocol REF missing before 'Data Transformation Name', found 'Term Accession Number'
inserting Protocol REF.3 at position 46
```

Example ISA-Tab dataset: https://github.com/CellMigStandOrg/CMSO-datasets/tree/master/cmsodataset0001-masuzzo/isa

Code: https://github.com/CellMigStandOrg/CMSO-datasets/blob/master/check_isa.py

**Comment by djcomlab** [comment] 2017-08-16 11:13
The problem is that the ISA-Tab preprocessor finds `___ Name` columns that are not immediately preceded by a `Protocol REF` column, it interprets the column as missing. However if there are `Parameter Value` columns after a valid `Protocol REF` (or one can also expect this behaviour with `Comment` columns too), where the expected name column should also appear in this context, the preprocessor incorrectly inserts a column when it shouldn't.

**Comment by agbeltran** [comment] 2017-08-16 14:54
Note that the code linked above is using the old parser 

```
import os
import glob

import isatools.io.isatab_parser as isatab_parser


def main():
    for d in glob.glob("cmso*/isa"):
        print("validating %s" % d)
        rec = isatab_parser.parse(os.path.abspath(d))
        assert hasattr(rec, "metadata")


if __name__ == "__main__":
main()
```

**Comment by djcomlab** [comment] 2017-10-06 10:18
This seems to be a problem with the `isatab_parser.StudyAssayParser._preprocess()` function only, and issue does not occur in the other preprocessor found in `isatab` package.

**Comment by djcomlab** [comment] 2017-10-06 13:41
Fixed in develop

**Closed by djcomlab** 2017-10-06 13:41 UTC
Labels: bug
