### ISSUE TITLE
isatab2json conversion throws AttributeError in createExecuteStudyProtocol() 

### ISSUE THREAD

**Issue by djcomlab** [ISA-tools/isa-api#43] opened 2015-12-23 13:40 UTC
Converting BII-I-1 is unsuccessful, throwing up the following error when running test_isatab2json.py and elsewhere:
```
Error
Traceback (most recent call last):
  File "/PycharmProjects/isa-api/tests/test_isatab2json.py", line 19, in test_bii_i_1_conversion
    isa_json = self.isatab2json.convert(test_data_dir, self.sample_data_dir)
  File "/PycharmProjects/isa-api/isatools/convert/isatab2json.py", line 49, in convert
    ("studies", self.createStudies(isa_tab.studies))
  File "//PycharmProjects/isa-api/isatools/convert/isatab2json.py", line 215, in createStudies
    ("processSequence", self.createProcessSequence(study.process_nodes, source_dict, sample_dict, data_dict)),
  File "/PycharmProjects/isa-api/isatools/convert/isatab2json.py", line 270, in createProcessSequence
    ("executesProtocol", self.createExecuteStudyProtocol(process_node_name, process_nodes[process_node_name])),
  File "/PycharmProjects/isa-api/isatools/convert/isatab2json.py", line 305, in createExecuteStudyProtocol
    ("name", process_node.protocol)
AttributeError: 'ProcessNodeRecord' object has no attribute 'protocol'
```

**Comment by agbeltran** [comment] 2016-01-06 14:42
I cannot reproduce this error when running in feat/conversion nor develop branches. Maybe you ran it from a branch which didn't have the latest code?

**Comment by djcomlab** [comment] 2016-01-06 14:49
I just now checked out and pulled for both develop and feat/conversion and still get the same error!

**Comment by agbeltran** [comment] 2016-01-06 14:52
Thanks for checking - the reason is some changes to the parser, I will push them soon.

**Comment by agbeltran** [comment] 2016-01-06 15:06
Should be fixed now - please reopen if it isn't.

**Closed by agbeltran** 2016-01-06 15:06 UTC
Labels: bug, convert
